services:

# ========================
# DATABASE
# ========================
  db:
    image: postgis/postgis:15-3.4
    container_name: geoavia_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      AIRFLOW_DB: ${AIRFLOW_DB}
    ports:
      - "${DB_EXT_PORT:-5433}:${DB_PORT:-5432}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/db:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

# ========================
# BACKEND SERVICE
# ========================
  backend:
    build: .
    container_name: geoavia_backend
    volumes:
      - ./backend/src:/app/src
    command: >
      bash -c "alembic upgrade head &&
               python -m uvicorn geoavia_backend.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "${API_PORT:-8000}:8000" # HOST:CONTAINER
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

# ========================
# AIRFLOW SERVICE
# ========================
  airflow:
    build: ./airflow_config
    container_name: geoavia_airflow
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      permission-fixer:
        condition: service_completed_successfully
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW_UID: 50000
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${AIRFLOW_DB}
      AIRFLOW_CONN_GEOAVIA_MAIN_CONN: postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    volumes:
      - ./airflow_config/dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
      - geo_data:/opt/airflow/data
      - ./airflow_config/plugins:/opt/airflow/plugins
      - ./tests:/opt/airflow/tests
      - ./init/airflow.sh:/opt/airflow/init_airflow.sh:ro
    ports:
      - "${AIRFLOW_PORT:-8080}:8080" # HOST:CONTAINER
    command: webserver

# ========================
# AIRFLOW SCHEDULER
# ========================
  airflow-scheduler:
    build: ./airflow_config
    container_name: geoavia_airflow_scheduler
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      permission-fixer:
        condition: service_completed_successfully
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW_UID: 50000
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${AIRFLOW_DB}
      AIRFLOW_CONN_GEOAVIA_MAIN_CONN: postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    volumes:
      - ./airflow_config/dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
      - geo_data:/opt/airflow/data
      - ./airflow_config/plugins:/opt/airflow/plugins
      - ./tests:/opt/airflow/tests
      - ./init/airflow.sh:/opt/airflow/init_airflow.sh:ro
    command: scheduler

# ========================
# AIRFLOW INITIALIZER
# ========================
  airflow-init:
    build: ./airflow_config
    depends_on:
      db:
        # It only tries to initialize airflow after the postgres database is created
        condition: service_healthy 
      permission-fixer:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      AIRFLOW_UID: 50000
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${AIRFLOW_DB}
    volumes:
      - ./init/airflow.sh:/init_airflow.sh
      - ./airflow_config/dags:/opt/airflow/dags
      - ./airflow_config/plugins:/opt/airflow/plugins
    command: bash /init_airflow.sh


# ========================
# PERMISSION FIXER
# ========================
  permission-fixer:
    image: alpine
    container_name: geoavia_permission_fixer
    command: chown -R 50000:0 /opt/airflow/data
    volumes:
      - geo_data:/opt/airflow/data

# ========================
# DATA PERSISTENCE
# ========================
volumes:
  postgres_data:
  airflow_logs:
  geo_data: