services:
  db:
    image: postgres:15
    container_name: geoavia_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: geoavia_users
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d

  backend:
    build: .
    container_name: geoavia_backend
    volumes:
      - ./backend/src:/app/src
    command: python -m uvicorn geoavia_backend.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: